### ISSUE TITLE
Fix ActiveRecord::ConnectionNotEstablished Database Connection Error

### ISSUE THREAD

**Issue by zehan12** [zehan12/Clinic360#5]
### Summary:
The application is failing to establish a database connection, resulting in the following error:

```
ActiveRecord::ConnectionNotEstablished
```

This occurs when the database configuration or connection setup is incorrect.

## Steps to Reproduce:

Start the Rails server:

```
rails server
```

Trigger any action that interacts with the database.

Observe the error:

![Screenshot from 2024-10-25 02-14-16](https://github.com/user-attachments/assets/4324acd0-d3f2-4966-9bab-7d2e673efae5)

#### 1. Update `database.yml`:

 Ensure your config/database.yml file is properly configured with the correct database settings.

Example configuration for PostgreSQL:

```yaml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: 'your_db_user'
  password:  'your_db_password'
  host: localhost
```
Replace your_db_user and your_db_password with the correct database credentials.
Ensure that the database name matches your project environment.

#### 2. Create and Setup the Database:

Run the following commands to create the database and apply migrations:

```bash
rails db:create
rails db:migrate
```
### Expected Behavior:
The Rails application should connect to the database successfully, allowing all database operations to proceed without errors.
